In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
test_df = pd.read_csv('/content/test.csv')
train_df = pd.read_csv('/content/train.csv')

# EDA AND DATA CLEANING

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:

train_df['HasCabin'] = train_df['Cabin'].notnull().astype(int)
test_df['HasCabin'] = test_df['Cabin'].notnull().astype(int)

In [ ]:
train_df = train_df.drop(columns='Cabin',axis=1)
test_df = test_df.drop(columns='Cabin',axis=1)

In [ ]:
train_df.value_counts()

PassengerId  Survived  Pclass  Name                                                 Sex     Age   SibSp  Parch  Ticket            Fare     Embarked  HasCabin
891          0         3       Dooley, Mr. Patrick                                  male    32.0  0      0      370376            7.7500   Q         0           1
1            0         3       Braund, Mr. Owen Harris                              male    22.0  1      0      A/5 21171         7.2500   S         0           1
2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599          71.2833  C         1           1
3            1         3       Heikkinen, Miss. Laina                               female  26.0  0      0      STON/O2. 3101282  7.9250   S         0           1
4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803            53.1000  S         1           1
                                                                                                                                                                ..
14           0         3       Andersson, Mr. Anders Johan                          male    39.0  1      5      347082            31.2750  S         0           1
13           0         3       Saundercock, Mr. William Henry                       male    20.0  0      0      A/5. 2151         8.0500   S         0           1
12           1         1       Bonnell, Miss. Elizabeth                             female  58.0  0      0      113783            26.5500  S         1           1
11           1         3       Sandstrom, Miss. Marguerite Rut                      female  4.0   1      1      PP 9549           16.7000  S         1           1
10           1         2       Nasser, Mrs. Nicholas (Adele Achem)                  female  14.0  1      0      237736            30.0708  C         0           1
Name: count, Length: 712, dtype: int64

In [ ]:
print(train_df.corr(numeric_only=True)["Survived"])

PassengerId   -0.005007
Survived       1.000000
Pclass        -0.338481
Age           -0.077221
SibSp         -0.035322
Parch          0.081629
Fare           0.257307
HasCabin       0.316912
Name: Survived, dtype: float64

In [ ]:
train_df = train_df.drop(columns='PassengerId',axis=1)
test_df = test_df.drop(columns='PassengerId',axis=1)

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Embarked  889 non-null    object
 10  HasCabin  891 non-null    int64
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [ ]:
train_df["Age"].fillna(train_df["Age"].median(), inplace=True)
test_df["Age"].fillna(test_df["Age"].median(), inplace=True)

train_df

/tmp/ipykernel_8623/1207819408.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df["Age"].fillna(train_df["Age"].median(), inplace=True)
/tmp/ipykernel_8623/1207819408.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_df["Age"].fillna(test_df["Age"].median(), inplace=True)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,1
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,0
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,1
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0

In [ ]:
train_df["Embarked"].fillna(
    train_df["Embarked"].mode()[0],
    inplace=True
)
test_df["Embarked"].fillna(
    test_df["Embarked"].mode()[0],
    inplace=True
)

/tmp/ipykernel_8623/787703859.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_df["Embarked"].fillna(
/tmp/ipykernel_8623/787703859.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_df["Embarked"].fillna(

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       891 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Embarked  891 non-null    object
 10  HasCabin  891 non-null    int64
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [ ]:
print(train_df.corr(numeric_only=True)["Survived"])

Survived    1.000000
Pclass     -0.338481
Age        -0.064910
SibSp      -0.035322
Parch       0.081629
Fare        0.257307
HasCabin    0.316912
Name: Survived, dtype: float64

In [ ]:
print(train_df["Ticket"].nunique())
print(train_df["Ticket"].count())

681
891

In [ ]:
print(train_df.corr(numeric_only=True)["Survived"])

Survived    1.000000
Pclass     -0.338481
Age        -0.064910
SibSp      -0.035322
Parch       0.081629
Fare        0.257307
HasCabin    0.316912
Name: Survived, dtype: float64

In [ ]:
train_df["FamilySize"] = (
    train_df["SibSp"] +
    train_df["Parch"] + 1
)
test_df["FamilySize"] = (
    test_df["SibSp"] +
    test_df["Parch"] + 1
)
train_df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin,FamilySize
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0,2
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1,2
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0,1
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1,2
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0,1
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,1,1
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,0,4
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,1,1
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0,1

In [ ]:
print(train_df.corr(numeric_only=True)["Survived"])

Survived      1.000000
Pclass       -0.338481
Age          -0.064910
SibSp        -0.035322
Parch         0.081629
Fare          0.257307
HasCabin      0.316912
FamilySize    0.016639
Name: Survived, dtype: float64

In [ ]:
train_df.groupby("FamilySize")["Survived"].mean()

FamilySize
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: Survived, dtype: float64

In [ ]:
train_df["IsAlone"] = (
    train_df["FamilySize"] == 1
).astype(int)

test_df["IsAlone"] = (
    test_df["FamilySize"] == 1
).astype(int)

In [ ]:
train_df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin,FamilySize,IsAlone
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0,2,0
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1,2,0
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0,1,1
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1,2,0
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0,1,1
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,1,1,1
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,0,4,0
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,1,1,1
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0,1,1

In [ ]:
train_df['Title'] = train_df['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)

test_df['Title'] = test_df['Name'].str.extract(r' ([A-Za-z]+)\.', expand=False)

In [ ]:
train_df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,HasCabin,FamilySize,IsAlone,Title
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0,2,0,Mr
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1,2,0,Mrs
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0,1,1,Miss
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1,2,0,Mrs
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0,1,1,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0,1,1,Rev
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,1,1,1,Miss
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S,0,4,0,Miss
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,1,1,1,Mr
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0,1,1,Mr

In [ ]:
train_df.drop("Name", axis=1, inplace=True)
test_df.drop("Name", axis=1, inplace=True)

In [ ]:
train_df.drop(["SibSp", "Parch"], axis=1, inplace=True)

test_df.drop(["SibSp", "Parch"], axis=1, inplace=True)

In [ ]:
train_df.drop("Ticket", axis=1, inplace=True)
test_df.drop("Ticket", axis=1, inplace=True)

In [ ]:
train_df

,Survived,Pclass,Sex,Age,Fare,Embarked,HasCabin,FamilySize,IsAlone,Title
0,0,3,male,22.0,7.2500,S,0,2,0,Mr
1,1,1,female,38.0,71.2833,C,1,2,0,Mrs
2,1,3,female,26.0,7.9250,S,0,1,1,Miss
3,1,1,female,35.0,53.1000,S,1,2,0,Mrs
4,0,3,male,35.0,8.0500,S,0,1,1,Mr
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,13.0000,S,0,1,1,Rev
887,1,1,female,19.0,30.0000,S,1,1,1,Miss
888,0,3,female,28.0,23.4500,S,0,4,0,Miss
889,1,1,male,26.0,30.0000,C,1,1,1,Mr
890,0,3,male,32.0,7.7500,Q,0,1,1,Mr

In [ ]:
cols = ['Sex','Embarked','Title']
train_df = pd.get_dummies(train_df, columns=cols)
test_df = pd.get_dummies(test_df, columns=cols)

In [ ]:
train_df

,Survived,Pclass,Age,Fare,HasCabin,FamilySize,IsAlone,Sex_female,Sex_male,Embarked_C,...,Title_Major,Title_Master,Title_Miss,Title_Mlle,Title_Mme,Title_Mr,Title_Mrs,Title_Ms,Title_Rev,Title_Sir
0,0,3,22.0,7.2500,0,2,0,False,True,False,...,False,False,False,False,False,True,False,False,False,False
1,1,1,38.0,71.2833,1,2,0,True,False,True,...,False,False,False,False,False,False,True,False,False,False
2,1,3,26.0,7.9250,0,1,1,True,False,False,...,False,False,True,False,False,False,False,False,False,False
3,1,1,35.0,53.1000,1,2,0,True,False,False,...,False,False,False,False,False,False,True,False,False,False
4,0,3,35.0,8.0500,0,1,1,False,True,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,13.0000,0,1,1,False,True,False,...,False,False,False,False,False,False,False,False,True,False
887,1,1,19.0,30.0000,1,1,1,True,False,False,...,False,False,True,False,False,False,False,False,False,False
888,0,3,28.0,23.4500,0,4,0,True,False,False,...,False,False,True,False,False,False,False,False,False,False
889,1,1,26.0,30.0000,1,1,1,False,True,True,...,False,False,False,False,False,True,False,False,False,False
890,0,3,32.0,7.7500,0,1,1,False,True,False,...,False,False,False,False,False,True,False,False,False,False

In [ ]:
train_df = train_df.astype(int)
train_df

,Survived,Pclass,Age,Fare,HasCabin,FamilySize,IsAlone,Sex_female,Sex_male,Embarked_C,...,Title_Major,Title_Master,Title_Miss,Title_Mlle,Title_Mme,Title_Mr,Title_Mrs,Title_Ms,Title_Rev,Title_Sir
0,0,3,22,7,0,2,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
1,1,1,38,71,1,2,0,1,0,1,...,0,0,0,0,0,0,1,0,0,0
2,1,3,26,7,0,1,1,1,0,0,...,0,0,1,0,0,0,0,0,0,0
3,1,1,35,53,1,2,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,3,35,8,0,1,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27,13,0,1,1,0,1,0,...,0,0,0,0,0,0,0,0,1,0
887,1,1,19,30,1,1,1,1,0,0,...,0,0,1,0,0,0,0,0,0,0
888,0,3,28,23,0,4,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
889,1,1,26,30,1,1,1,0,1,1,...,0,0,0,0,0,1,0,0,0,0
890,0,3,32,7,0,1,1,0,1,0,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Pclass        418 non-null    int64
 1   Age           418 non-null    float64
 2   Fare          417 non-null    float64
 3   HasCabin      418 non-null    int64
 4   FamilySize    418 non-null    int64
 5   IsAlone       418 non-null    int64
 6   Sex_female    418 non-null    bool
 7   Sex_male      418 non-null    bool
 8   Embarked_C    418 non-null    bool
 9   Embarked_Q    418 non-null    bool
 10  Embarked_S    418 non-null    bool
 11  Title_Col     418 non-null    bool
 12  Title_Dona    418 non-null    bool
 13  Title_Dr      418 non-null    bool
 14  Title_Master  418 non-null    bool
 15  Title_Miss    418 non-null    bool
 16  Title_Mr      418 non-null    bool
 17  Title_Mrs     418 non-null    bool
 18  Title_Ms      418 non-null    bool
 19  Title_Rev     418 non-null    bool
dtypes: bool(14), float64(2), int64(4)
memory usage: 25.4 KB

In [ ]:
test_df['Fare'].fillna(test_df['Fare'].median(),inplace=True)

/tmp/ipykernel_8623/271438003.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_df['Fare'].fillna(test_df['Fare'].median(),inplace=True)

In [ ]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 20 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Pclass        418 non-null    int64
 1   Age           418 non-null    float64
 2   Fare          418 non-null    float64
 3   HasCabin      418 non-null    int64
 4   FamilySize    418 non-null    int64
 5   IsAlone       418 non-null    int64
 6   Sex_female    418 non-null    bool
 7   Sex_male      418 non-null    bool
 8   Embarked_C    418 non-null    bool
 9   Embarked_Q    418 non-null    bool
 10  Embarked_S    418 non-null    bool
 11  Title_Col     418 non-null    bool
 12  Title_Dona    418 non-null    bool
 13  Title_Dr      418 non-null    bool
 14  Title_Master  418 non-null    bool
 15  Title_Miss    418 non-null    bool
 16  Title_Mr      418 non-null    bool
 17  Title_Mrs     418 non-null    bool
 18  Title_Ms      418 non-null    bool
 19  Title_Rev     418 non-null    bool
dtypes: bool(14), float64(2), int64(4)
memory usage: 25.4 KB

In [ ]:
test_df = test_df.astype(int)
test_df

,Pclass,Age,Fare,HasCabin,FamilySize,IsAlone,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Title_Col,Title_Dona,Title_Dr,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Ms,Title_Rev
0,3,34,7,0,1,1,0,1,0,1,0,0,0,0,0,0,1,0,0,0
1,3,47,7,0,2,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0
2,2,62,9,0,1,1,0,1,0,1,0,0,0,0,0,0,1,0,0,0
3,3,27,8,0,1,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0
4,3,22,12,0,3,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,3,27,8,0,1,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0
414,1,39,108,1,1,1,1,0,1,0,0,0,1,0,0,0,0,0,0,0
415,3,38,7,0,1,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0
416,3,27,8,0,1,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0
417,3,27,22,0,3,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0

# Feature Scaling

In [ ]:
X = train_df.drop(columns='Survived')
y = train_df['Survived']

In [ ]:
X

,Pclass,Age,Fare,HasCabin,FamilySize,IsAlone,Sex_female,Sex_male,Embarked_C,Embarked_Q,...,Title_Major,Title_Master,Title_Miss,Title_Mlle,Title_Mme,Title_Mr,Title_Mrs,Title_Ms,Title_Rev,Title_Sir
0,3,22,7,0,2,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
1,1,38,71,1,2,0,1,0,1,0,...,0,0,0,0,0,0,1,0,0,0
2,3,26,7,0,1,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,1,35,53,1,2,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,3,35,8,0,1,1,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,27,13,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
887,1,19,30,1,1,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
888,3,28,23,0,4,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
889,1,26,30,1,1,1,0,1,1,0,...,0,0,0,0,0,1,0,0,0,0
890,3,32,7,0,1,1,0,1,0,1,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
X.value_counts()

Pclass  Age  Fare  HasCabin  FamilySize  IsAlone  Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S  Title_Capt  Title_Col  Title_Countess  Title_Don  Title_Dr  Title_Jonkheer  Title_Lady  Title_Major  Title_Master  Title_Miss  Title_Mlle  Title_Mme  Title_Mr  Title_Mrs  Title_Ms  Title_Rev  Title_Sir
3       28   7     0         1           1        0           1         0           0           1           0           0          0               0          0         0               0           0            0             0           0           0          1         0          0         0          0            25
                                                  1           0         0           1           0           0           0          0               0          0         0               0           0            0             1           0           0          0         0          0         0          0            16
                                                  0           1         0           1           0           0           0          0               0          0         0               0           0            0             0           0           0          1         0          0         0          0            14
                                                                        1           0           0           0           0          0               0          0         0               0           0            0             0           0           0          1         0          0         0          0            14
             8     0         1           1        0           1         0           0           1           0           0          0               0          0         0               0           0            0             0           0           0          1         0          0         0          0            14
                                                                                                                                                                                                                                                                                                                         ..
2       17   10    0         1           1        1           0         0           0           1           0           0          0               0          0         0               0           0            0             1           0           0          0         0          0         0          0             1
             12    0         1           1        1           0         1           0           0           0           0          0               0          0         0               0           0            0             1           0           0          0         0          0         0          0             1
        18   13    0         1           1        0           1         0           0           1           0           0          0               0          0         0               0           0            0             0           0           0          1         0          0         0          0             1
                             3           0        1           0         0           0           1           0           0          0               0          0         0               0           0            0             1           0           0          0         0          0         0          0             1
        7    26    0         3           0        1           0         0           0           1           0           0          0               0          0         0               0           0            0             1           0           0          0         0          0         0          0             1
Name: count, Length: 686, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

cols = ['Pclass', 'Age', 'Fare', 'FamilySize']

X_scaled = X.copy()
test_df_scaled = test_df.copy()

X_scaled[cols] = scaler.fit_transform(X[cols])

test_df_scaled[cols] = scaler.transform(test_df[cols])
X_scaled

,Pclass,Age,Fare,HasCabin,FamilySize,IsAlone,Sex_female,Sex_male,Embarked_C,Embarked_Q,...,Title_Major,Title_Master,Title_Miss,Title_Mlle,Title_Mme,Title_Mr,Title_Mrs,Title_Ms,Title_Rev,Title_Sir
0,0.827377,-0.564145,-0.498948,0,0.059160,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
1,-1.566107,0.664649,0.789405,1,0.059160,0,1,0,1,0,...,0,0,0,0,0,0,1,0,0,0
2,0.827377,-0.256947,-0.498948,0,-0.560975,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,-1.566107,0.434250,0.427056,1,0.059160,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0.827377,0.434250,-0.478817,0,-0.560975,1,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,-0.369365,-0.180147,-0.378164,0,-0.560975,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
887,-1.566107,-0.794544,-0.035946,1,-0.560975,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
888,0.827377,-0.103348,-0.176859,0,1.299429,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
889,-1.566107,-0.256947,-0.035946,1,-0.560975,1,0,1,1,0,...,0,0,0,0,0,1,0,0,0,0
890,0.827377,0.203851,-0.498948,0,-0.560975,1,0,1,0,1,...,0,0,0,0,0,1,0,0,0,0

# Models Scaled

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
models = {
    "KNN": (
        KNeighborsClassifier(),
        {
            "n_neighbors": [3, 5, 7, 9, 11],
            "weights": ["uniform", "distance"],
            "metric": ["euclidean", "manhattan"]
        }
    ),

    "Logistic Regression": (
        LogisticRegression(max_iter=1000),
        {
            "C": [0.01, 0.1, 1, 10, 100],
            "solver": ["liblinear", "lbfgs"],
            "penalty": ["l2"]
        }
    ),
    "SVM": (
    SVC(),
    {
        "C": [0.1, 1, 10],
        "kernel": ["linear", "rbf"]
    }
)
}

base_normal = {}

for model_name, (model, params) in models.items():

    grid = GridSearchCV(
        model,
        params,
        cv=5,
        scoring='accuracy'
    )

    grid.fit(X_scaled, y)

    print(f"\n{model_name}")

    base_normal[model_name] = grid.best_estimator_

    print("Best Params:", grid.best_params_)

    print("Best Accuracy:", grid.best_score_)

KNN
Best Params: {'metric': 'manhattan', 'n_neighbors': 9, 'weights': 'uniform'}
Best Accuracy: 0.822666499278137

Logistic Regression
Best Params: {'C': 10, 'penalty': 'l2', 'solver': 'liblinear'}
Best Accuracy: 0.8260372857949909

SVM
Best Params: {'C': 1, 'kernel': 'rbf'}
Best Accuracy: 0.8338836231247253

# MODEL'S

In [ ]:
X

,Pclass,Age,Fare,HasCabin,FamilySize,IsAlone,Sex_female,Sex_male,Embarked_C,Embarked_Q,...,Title_Major,Title_Master,Title_Miss,Title_Mlle,Title_Mme,Title_Mr,Title_Mrs,Title_Ms,Title_Rev,Title_Sir
0,3,22,7,0,2,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
1,1,38,71,1,2,0,1,0,1,0,...,0,0,0,0,0,0,1,0,0,0
2,3,26,7,0,1,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,1,35,53,1,2,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,3,35,8,0,1,1,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,27,13,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
887,1,19,30,1,1,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
888,3,28,23,0,4,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
889,1,26,30,1,1,1,0,1,1,0,...,0,0,0,0,0,1,0,0,0,0
890,3,32,7,0,1,1,0,1,0,1,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

models = {
        "Decision Tree": (
          DecisionTreeClassifier(random_state=42),
          {
              "criterion": ["gini", "entropy"],
              "max_depth": [3, 5, 7, 10],
              "min_samples_split": [2, 5, 10]
          }
        ),
        "Random Forest": (
    RandomForestClassifier(random_state=42),
    {
    "n_estimators": [50, 100],
    "max_depth": [3, 5],
    "min_samples_split": [2, 5]
}
),
        "XGBoost": (
    XGBClassifier(
        eval_metric='logloss',
        random_state=42
    ),
    {
    "n_estimators": [50, 100],
    "max_depth": [2, 3, 4],
    "learning_rate": [0.05, 0.1],
}
)
}

best_models = {}


for model_name, (model, params) in models.items():
      grid = GridSearchCV(
            model,
            params,
            cv=5,
            scoring='accuracy'
        )

      grid.fit(X, y)

      print(f"\n{model_name}")
      best_models[model_name] = grid.best_estimator_

      print("Best Params:", grid.best_params_)

      print("Best Accuracy:", grid.best_score_)

Decision Tree
Best Params: {'criterion': 'gini', 'max_depth': 3, 'min_samples_split': 2}
Best Accuracy: 0.8181721172556651

Random Forest
Best Params: {'max_depth': 5, 'min_samples_split': 5, 'n_estimators': 100}
Best Accuracy: 0.8327537505492437

XGBoost
Best Params: {'learning_rate': 0.1, 'max_depth': 4, 'n_estimators': 100}
Best Accuracy: 0.8305128366078713

In [ ]:
original_test_df = pd.read_csv("/content/test.csv")

passenger_ids = original_test_df["PassengerId"]

best_rf = best_models["Random Forest"]

predictions = best_rf.predict(test_df)

submission = pd.DataFrame({
    "PassengerId": passenger_ids,
    "Survived": predictions
})

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- Title_Dona
Feature names seen at fit time, yet now missing:
- Title_Capt
- Title_Countess
- Title_Don
- Title_Jonkheer
- Title_Lady
- ...

In [ ]:
submission.to_csv("submission.csv", index=False)